// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzzCpX6Qlar5_GuEn6fU9OJZiEFx2OJPA',
    appId: '1:422412778152:web:622a0d81c8f4752f24e09d',
    messagingSenderId: '422412778152',
    projectId: 'ppdeli-f07a9',
    authDomain: 'ppdeli-f07a9.firebaseapp.com',
    databaseURL: 'https://ppdeli-f07a9-default-rtdb.firebaseio.com',
    storageBucket: 'ppdeli-f07a9.firebasestorage.app',
    measurementId: 'G-BT2NW6JTWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClR9gV_285DgJviVaWvZrgkc2_Bb2wNwQ',
    appId: '1:422412778152:android:bbe20039b88aa6f124e09d',
    messagingSenderId: '422412778152',
    projectId: 'ppdeli-f07a9',
    databaseURL: 'https://ppdeli-f07a9-default-rtdb.firebaseio.com',
    storageBucket: 'ppdeli-f07a9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddEFHQsX3zUipextEB1iQOT9_pI6IFVo',
    appId: '1:422412778152:ios:fdc63fc2e014d92e54e7d2',
    messagingSenderId: '422412778152',
    projectId: 'ppdeli-f07a9',
    databaseURL: 'https://ppdeli-f07a9-default-rtdb.firebaseio.com',
    storageBucket: 'ppdeli-f07a9.firebasestorage.app',
    androidClientId: '422412778152-ddcciicjsbujumnifdemkp8aldro0qbr.apps.googleusercontent.com',
    iosClientId: '422412778152-47s16topcf697a4d9dcng0vsd5ssub8t.apps.googleusercontent.com',
    iosBundleId: 'com.ppdeli.market',
  );
}
